GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs

Content-Type: application/json

{
    "author": "sarang wadode",
    "title": "my first blog",
    "url": "http://blogs/sarangwadode/firstblog",
    "likes": 123 
}