GET https://shy-moon-8318.fly.dev/api/persons

###

GET http://localhost:3001/api/persons/

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "sarang",
    "number": "456464"
}